### ISSUE TITLE
Boot failed, display OCS：No schema for Type at 0 index，context <ReservedMemory>

### ISSUE THREAD

**Issue by root-mido** [GGorAA/Hackintosh-840#10]
help,use "Hackintosh 840 4.0 Stable-->EFI.ZIP",fail
display: “OCS：No schema for Type at 0 index，context <ReservedMemory>”
my computer model HP 840 G3
Install version: Big Sur 11.0 Public Beta 3

**Comment by GGorAA** [comment]
Yes, issue exists
I actually forgot to update the repo, sorry XD

**Comment by GGorAA** [comment]
I am updating OpenCore from nightly version to official release, I will test out the updates and then publish the update

**Comment by GGorAA** [comment]
New release is here, try it out!

**Comment by root-mido** [comment]
Thank you for reply and fix , It big helpful for me ,gratitude again

**Comment by GGorAA** [comment]
Done!
