### ISSUE TITLE
how about newer Bios Versions for HP 840 G3?

### ISSUE THREAD

**Issue by DominikHackintosh** [GGorAA/Hackintosh-840#11]
Hi, i had big problems with my HP 840 G4, only up to Bios Version P78 v.1.29 / v.1.3.1 was bootable by Clover/openCore. now i found a patch and a ACPI Solution from another repository of hp 850 g5. this works great! you can find it on my github. Greetings from hungary

**Comment by GGorAA** [comment]
Well, you have the 840 G4, which is not supported. But, if the patch won't break the 840 G4 configuration, I will apply that patch and publish new update

**Comment by GGorAA** [comment]
Also, I actually forgot to update the BIOS of my laptop, because of the main rule of programmers: "If it is working, DO NOT TOUCH" XD

**Comment by DominikHackintosh** [comment]
[SSDT-SET-STAS.aml.zip](https://github.com/GGorAA/Hackintosh-840/files/5529954/SSDT-SET-STAS.aml.zip)
try this file in your ACPI Folder, thats the better way to fix new bios, there is also a acpi patch you will find it in my config, its the first patch under A'Cpi

**Comment by GGorAA** [comment]
Where us your config? :D

**Comment by GGorAA** [comment]
Updated the config, after the reboot I will tell the results of the patch

**Comment by GGorAA** [comment]
Successfully rebooted, everything works fine after all. I will publish an update soon! I think the issue is resolved :D
