### ISSUE TITLE
Unable to located Postinstall.zip 

### ISSUE THREAD

**Issue by ceanth** [GGorAA/Hackintosh-840#15]
Hello,

I am following your guide and it mentions:

"Download the Postinstall.zip package from release that you are downloading"

Maybe I am missing something but I do not seem to see this zip file located within the releases section or the file repository.

Many thanks

**Comment by GGorAA** [comment]
Oh, sorry, I completely forgot to edit the README
Actually I removed Postinstall.zip from the releases, and you will need to download Hackintool and other things from their respective places

**Comment by GGorAA** [comment]
Fixed README, is it good?

**Comment by GGorAA** [comment]
Done
