### ISSUE TITLE
Not network

### ISSUE THREAD

**Issue by MartianPathFinder** [ggoraa/Hackintosh-840#17]
I have HP 840 g3 with spec:
BIOS: N75 (ver. 01.49)
CPU: Intel Core i5 6300U @ 2.4 GHz (Skylake, 2 cores, 4 HT)
Chipset: Intel 100 Series
GPU: integrated Intel HD Graphics 520
Display: 1920x1080
Ethernet: Intel I219LM
Wifi + BT: 8260 

It was installed Big Sur 11.2.2. And WiFi isn't fast, but work.

Mute button was hidden and sound card doesn't work, not headphone, not speakers.
I changed config.plist: added alcid=3, and mute button show and enable. But not finding any sound device.
I tried change AppleALC file from Catalina 10.15.7, but unsuccessful.

And ethernet doesn't work. Doesn't find ethernet card. I tried change kext: IntelMausi.kext. But unsuccessful.

Do you have any idea, how fix this issues?
Thank you.

**Comment by ggoraa** [comment]
Hello!
Sorry for being THAT slow, I haven't much visited this repo lately.
About your issues. You need to find your sound device using a tutorial on Dortania's website. btw thx for mute button hack xD
Ethernet. I actually dunno why it is broken. It should just "work".
