### ISSUE TITLE
No macOS option in OpenCore Boot Menu

### ISSUE THREAD

**Issue by Piipperi** [ggoraa/Hackintosh-840#18]
I first had to update OpenCore on the EFI provided, before doing that I was stuck on a black screen. But I got shortly after that stuck on the OC Boot Menu with no macOS option (I have the USB plugged in ofc, and I haven't yet installed macOS)
![IMG_3213](https://user-images.githubusercontent.com/29174220/119357801-a4cb8780-bcb0-11eb-98ba-f5c4d0f34d89.jpeg)

**Comment by ggoraa** [comment]
That's actually odd. I have not experienced that before
Can you post here more details about this?

**Comment by Piipperi** [comment]
What details do you need? I created a macOS 11.2.3 USB installer as usual, and then put the EFI folder you provided. For some reason, It only gave me a black screen, and nothing else. Then, I updated the OC inside the folder to 0.6.9 and while now I get to the boot menu, as shown in the image there is no macOS found. People were telling me in Discord that it's an issue with the SATA interface (but logically of course that cannot be true really, not sure what were they onto), but instead I'm suggesting there's something wrong with the USB drivers. It can boot to the OC boot menu, but it can't find a bootable OS from the USB.

Just for an FYI if it helps, the keyboard does work on this screen.

**Comment by ggoraa** [comment]
So there are several cases that can lead to this issue:
1. Downloaded EFI was corrupt, and you need to re-download it
2. Your drive is already dying, so it causes this 
3. You made the usb installer already broken
4. USB port is broken

I think this is one of those, because my EFI and installers I make are very much working

**Comment by ggoraa** [comment]
I will try to release a new version of EFI, with updated OpenCore to 0.7.0 and some more minor updates
You will later try it out and say whether it fixed the issue or not

**Comment by ggoraa** [comment]
So, I investigated the issue by actually trying to install macOS from a flash drive. I also ended up in this. So not only you have this issue, me too basically

**Comment by ggoraa** [comment]
Found the cause. OpenHfPlus.efi was not loading

**Comment by Piipperi** [comment]
Is a fixed build coming soon then, if it's not fixed already?
Also, an additional question, does 11.4 work with this OC config or not? The readme says only up to 11.2.3 is supported

**Comment by ggoraa** [comment]
Yes, it works with 11.4, and latest beta even supports Monterey Beta 1
I will later publish a beta 2 with a fix for the installer, and support for Monterey Beta 2

**Comment by ggoraa** [comment]
Add it to OpenCore config. You can find a tutorial on the web for that

**Comment by meishier** [comment]
same issue

**Comment by ggoraa** [comment]
Did you use the latest release?

**Comment by KittyDev18** [comment]
Using the latest version still same issue 🥺

**Comment by ggoraa** [comment]
That's odd

**Comment by ggoraa** [comment]
Oh
Found the issue, I forgot to update the config

**Comment by Arechok** [comment]
For me it still exists. And by the way, what do I need to change in ProperTree, so it'll work well, because, like, I only see Windows option. Even "Reset NVRAM" didn't appear. How to solve it?

**Comment by ggoraa** [comment]
God damn. this is emberassin
fixing already, very sorry about issues 😓

**Comment by Arechok** [comment]
Ok, I'll wait...

**Comment by ggoraa** [comment]
Pushed new changes, you can try them out

**Comment by Arechok** [comment]
Where can I check it?

**Comment by wiegell** [comment]
This helped me: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/opencore-issues.html#can-t-see-macos-partitions

**Comment by ggoraa** [comment]
Thanks! I will implement them in a new update
I also got a broken hackintosh because s t u p i d, and for it to work again I updated opencore to 0.7.6

**Comment by Winksplorer** [comment]
I Am Getting The Same Issue.

**Comment by partnerparticle** [comment]
I am also getting the same issue. I am ok with OC 0.6.7, but after trying to update to 0.7.6 I don't have the macos menu.. I also tried with 0.7.5, same issue.
in my config.plist for 0.7.6 I have:
```
			<dict>
				<key>Arguments</key>
				<string></string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>Path</key>
				<string>HfsPlus.efi</string>
			</dict>

```

Any suggestions?

**Comment by mickulin** [comment]
Also getting the same issue.

**Comment by alfatihart** [comment]
same issue..

**Comment by pensilberwarna** [comment]
same issue, please help

**Comment by Elia99Best** [comment]
Same issue here

**Comment by voltangle** [comment]
Finally pushed new changes
I'm very sorry for this kind of a delay, issues with college :(

**Comment by I-Like-Hackintosh** [comment]
i know how to fix it !!!!! i just use the https://opencore.slowgeek.com **althought its stop update to 0.6.6** but i see the problum with self editing config.plist problum is we need to add apple event  in UEFI/ProtocolOverrides boolean =0 
ignore the UEFI should be 18 you see there got apple event there before that i didnt add and its dont work(IMAGE)
THAT WORKS FOR ME (my device information below) 
<img width="434" alt="Screenshot 2021-12-23 140536" src="https://user-images.githubusercontent.com/96582504/147251424-a8785be4-2668-4848-8593-13e2f2876cdd.png">

_**(Lenovo Yoga slim7 i7-1065g7 14IIL05)
Nvidia MX350 
Iris-Plus_Graphices
Ice-Lake**_
**BUT AFTER THAT WHEN I BOOT IT I STUCK ON BLACK SCREEN I STILL FIXING THE PROBLUM I HOPE SOMEONE HELP ME** 
[my plist.txt](https://github.com/ggoraa/Hackintosh-840/files/7769785/my.plist.txt)
 **I SAY AGAIN ,I STILL NOT FIX THE PROBLUM AFTER I BOOT !
 JUST TRY IF YOU WANT ,BUT YOU SHOULD OPEN A NEW .plist FILE TO BOOT** (i hope you try and tell me xd)
if its work tell me :)

**Comment by I-Like-Hackintosh** [comment]
tell me every thing you got and please take photo as you can please please please

**Comment by I-Like-Hackintosh** [comment]
If anyone same as me is black screen i will tell him 
**YOU DIDNT MAKE A ESP FOR THE DRIVER 
I JUST KNOW THAT 
ACTUALLY I THINKNO ONE SAME AS ME**

**Comment by furkankadioglu** [comment]
Hello @ggoraa,

Sorry but same issue here, version 0.7.6

**Comment by voltangle** [comment]
2ait wOt
how
lemme check

**Comment by voltangle** [comment]
I can't reproduce this, the OpenHfsPlus.efi driver is present in Drivers folder, and an appropriate record in `config.plist` is also there
![image](https://user-images.githubusercontent.com/61655029/147662145-814d0291-ca04-4162-87db-a36027f3ab2a.png)

**Comment by partnerparticle** [comment]
For Those who have the macOS option not showing up issue with Mojave and Catalina (should work with Big Sur), read the guide part about UEFI/APFS [https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/haswell.html#uefi](url)
"By default, OpenCore only loads APFS drivers from macOS Big Sur and newer. If you are booting macOS Catalina or earlier, you may need to set a new minimum version/date. Not setting this can result in OpenCore not finding your macOS partition!"

So set your MinVersion and MinDate accordingly! ( I tried with -1, and it showed my Mojave partition, so for me it works). I hope this will solve this issue for the affected people.
The config.plist in the repo has values 0, and those do not work for this case, you need to set them to either -1 or the proper values, as per guide.

@ggoraa , I assume you cannot reproduce because you are using Big Sur or newer?

**Comment by voltangle** [comment]
nope, i am on latest monterey

**Comment by partnerparticle** [comment]
Ok, that is in the category "Big Sur or newer", as explained in the guide, thats why its working for you :)
Thanks for confirming

**Comment by Manuudatu00** [comment]
I have the same problem

**Comment by I-Like-Hackintosh** [comment]
I know how Just add "Apple Event   boolean     0  " in UEFI/ProtocolOverrides 
 i just success i am a laptop lenovo slim 7 i71065g7

**Comment by voltangle** [comment]
Well, if the issue is still present for some, then please follow the advice above. The config currently only supports Monterey, if there are any issues on OSes prior to it, please, fix them by yourself by looking into documentation and some basic troubleshooting. I am only providing support for Monterey

**Comment by I-Like-Hackintosh** [comment]
dont say this ~~~ i think if some one cant do this because the OC cant found Drivers i think because after OC:0.6.9 the sanpper 
make drivers a Dictionary you should change bake Drivers dictionary to String :1st_place_medal:

**Comment by I-Like-Hackintosh** [comment]
i think this work for non-monterey

**Comment by Sonoman71** [comment]
> dont say this ~~~ i think if some one cant do this because the OC cant found Drivers i think because after OC:0.6.9 the sanpper
> make drivers a Dictionary you should change bake Drivers dictionary to String 🥇

Sorry pal, I'm having this issue too(OC doesn't give me even the possibility to install, there's no such an option in the menu).R U saying I should change Drivers Section on my config.plist from Array to String? Thanks in advance!

**Comment by Sonoman71** [comment]
Ok. After 8 hours of coming and going doing test I managed to fix this. I just put MinVersion and MinDate to -1 AND aded OpenHFSPlus.efi to the Drivers Folder AND declared it under Drivers in the config.plist.
I'm installing Big Sur.

**Comment by thuyahtut** [comment]
I have same issue with OC 0.7.7 and latest monterey. I hope next version will be fix it.
**May The Force Be With Us.**

**Comment by osc-kelns429** [comment]
When you get to that screen try pressing the Space key. I accidentally pressed the Space key and the options appeared (In my case there was only the option to boot into Windows, no option to Reset VRAM)

**Comment by rahulgwebdev** [comment]
Okay, I solved for me in opencore 77, make these following changes in config.plist, it should work for you as well

```
<key>HideAuxiliary</key>
<false/>
```

```
<key>Auxiliary</key>
<false/>
```

**Comment by 1amSumit** [comment]
IA MFACING THE SAME ISSUE

**Comment by rahulgupta8914** [comment]
> IA MFACING THE SAME ISSUE


it should solve the issue,
[
](https://github.com/ggoraa/Hackintosh-840/issues/18#issuecomment-1017257401)

 if not, can you give me your config.plist, I would like to try if i can help
