### ISSUE TITLE
Bios version

### ISSUE THREAD

**Issue by mirzam711** [ggoraa/Hackintosh-840#20]
Can you please provide you exact bios version because this EFI not working on my latest bios.
During installation laptop restart and after that just restating again and again nothing else happen.

**Comment by ggoraa** [comment]
Maybe because it is poorly setup. I have latest UEFI too, and everything works fine

**Comment by mirzam711** [comment]
Can you please guide me how to setup uefi Because i change all bios settings as mentioned in post and paste your efi folder in my usb drive's efi partition.

**Comment by ggoraa** [comment]
https://github.com/kreizlie/HP-EliteBook-840-G4-Hackintosh#bios-setup
