### ISSUE TITLE
battery

### ISSUE THREAD

**Issue by nadertawah** [ggoraa/Hackintosh-840#25]
battery icon/percentage isn't showing even though it's checked in the settings

**Comment by ggoraa** [comment]
Idk, not an issue for me
What device you have exactly?

**Comment by nadertawah** [comment]
HP EliteBook 840 G3 
Intel Core i5-6300U
Intel HD Graphics 520

**Comment by ggoraa** [comment]
Hmm, everything is basically the same as for me
What OS are you trying to install?

**Comment by nadertawah** [comment]
11.2.3

**Comment by ggoraa** [comment]
Try Monterey, it should work there
Works for me anyways

**Comment by nadertawah** [comment]
i tried and it didn't work either until i tried jake lo's latest efi and it's flawless

**Comment by ggoraa** [comment]
Nice
That's good to hear! I think the issue is now resolved, am I right?

**Comment by ggoraa** [comment]
Nice!
