### ISSUE TITLE
Trackpad disables after clicking Print Screen

### ISSUE THREAD

**Issue by GGorAA** [GGorAA/Hackintosh-840#4]
This is a "feature" of VoodooPS2Controller. Im now searching for how to disable that "feature"

**Comment by DominikHackintosh** [comment]
i think this is a feature, i even use it because often use mouse and so i turn off trackpad especially when writing alot, this prevents wrong inputs.... ;)

**Comment by GGorAA** [comment]
Well, that thing disturbs me a lot. I am typing something, then I press backspace, miss click on print screen, and I can't move my mouse anymore using my trackpad. And also, this feature is not present on real Macs, so I consider removing it :D

**Comment by ReQuasimodo** [comment]
turn on in bios "Launch Hotkeys without Fn Keypress" and replace the SSDT-840G3 with mine <a href="https://github.com/ReQuasimodo/HP-elitebook-840-g3-Hackintosh/blob/master/EFI/EFI/OC/ACPI/SSDT-840G3.aml">SSDT-840G3.aml</a>

**Comment by GGorAA** [comment]
I moved to Launch Hotkeys without Fn Keypress even before, because I wanted to change display brightness and system volume with one hand. But thanks for providing an SSDT, I will try it :D

**Comment by GGorAA** [comment]
Actually, it works! I will publish an update later
