### ISSUE TITLE
Boot chime plays only in headphones

### ISSUE THREAD

**Issue by ggoraa** [ggoraa/Hackintosh-840#6]

**Comment by GGorAA** [comment]
Found the issue: the wrong audio device was selected in `config.plist`. I am now working on finding that audio device

**Comment by DominikHackintosh** [comment]
did you find a solution for it? i  was trying on my hp840 g4 but with no success :(

**Comment by GGorAA** [comment]
Nope, haven't found

**Comment by GGorAA** [comment]
I think the issue is in PCI device path. It is pointing to the mini-jack port instead of speakers

**Comment by Human7900** [comment]
@ggoraa Any update?

**Comment by ggoraa** [comment]
Nope, nothing, i am unable to find the right device path for the thing

**Comment by ggoraa** [comment]
redirected to #19
